name: Build

on:
  push:
    branches:
      - master
      - actions
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: docker://devkitpro/devkita64
    steps:
    - name: Update dependencies
      run: |
        dkp-pacman -Syu --noconfirm switch-dev switch-glm switch-libjpeg-turbo devkitARM devkitarm-rules hactool
        apt-get update && apt-get install git zip python2 python2.7 python-pip -y
        rm /usr/bin/python
        ln -s /usr/bin/python2.7 /usr/bin/python
        python -m pip install lz4 pycryptodome
    - uses: actions/checkout@v3
    - name: Make it a safe directory
      run: git config --global --add safe.directory '*'
    - name: Run build
      run: make
    - run: ls
    - name: Upload
      uses: actions/upload-artifact@v3
      with:
        name: Atmosphere
        path: |
          out/nintendo_nx_arm64_armv8a/release/
          !**/*-dirty.zip